version: "3.9"

services:
  aggregator:
    build: ./aggregator
    ports:
      - "8080:8080"
    depends_on:
      - storage
      - broker
    environment:
      DATABASE_URL: postgresql://user:pass@storage:5432/db
      REDIS_URL: redis://broker:6379

  publisher:
    build: ./publisher
    depends_on:
      - aggregator

  broker:
    image: redis:7-alpine
    volumes:
      - broker_data:/data

  storage:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./aggregator/app/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data:
  broker_data:
